#ifndef	__DDR_LAYOUT_ADVCA__
#define	__DDR_LAYOUT_ADVCA__

#define SSA_LEN_IMG_HEADER_SIGN         (256)
#define SSA_LEN_IMG_HEADER_SIGN_POS     (16)
#define SSA_LEN_IMG_HEADER              (SSA_LEN_IMG_HEADER_SIGN + SSA_LEN_IMG_HEADER_SIGN_POS)

#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0 - SSA_LEN_IMG_HEADER)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0 - SSA_LEN_IMG_HEADER)
#define DDR_LAYOUT_START_BOOTARGS		(0x08000000)
#define DDR_LAYOUT_START_RESERVE		(0x0C100000)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_BOOTARGS		(0x00100000)
#define DDR_LAYOUT_SIZE_RESERVE		(0x19000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x04000000)

#define	DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define	DDR_LAYOUT_END_BOOTARGS		(DDR_LAYOUT_START_BOOTARGS + DDR_LAYOUT_SIZE_BOOTARGS)
#define	DDR_LAYOUT_END_RESERVE		(DDR_LAYOUT_START_RESERVE + DDR_LAYOUT_SIZE_RESERVE)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)

#endif