/******************************************************************************

  Copyright (C), 2018, Hisilicon Tech. Co., Ltd.

 ******************************************************************************
  File Name     :
  Version       : Initial Draft
  Author        : Device Chipset STB Development Dept
  Created       : 2018/
  Description   :
  History       :
  1.Date        : 2018/
    Author      : sdk
    Modification: Created file

*******************************************************************************/
#ifndef	__DDR_LAYOUT_BASIC__
#define	__DDR_LAYOUT_BASIC__

#if	defined(CONFIG_ARCH_HI3798MV310)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x05100000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3798MV310********/

#elif defined(CONFIG_ARCH_HI3798MV2X)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3798MV2X********/

#elif defined(CONFIG_ARCH_HI3796MV2X)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3796MV2X********/

#elif defined(CONFIG_ARCH_HI3798MX)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3798MX********/

#elif defined(CONFIG_ARCH_HI3798CV2X)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3798CV2X********/

#elif defined(CONFIG_ARCH_HI3716MV430)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x600000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3716MV430********/

#elif defined(CONFIG_ARCH_HI3716MV410)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3716MV410********/

#elif defined(CONFIG_ARCH_HI3716MV420N)
#define DDR_LAYOUT_START_KERNEL		(0x01FFFFC0)
#define DDR_LAYOUT_START_LOADER		(0x01FFFFC0)
#define DDR_LAYOUT_START_TEEOS		(0x0801E000)
#define DDR_LAYOUT_START_ROOTFS		(0x4000000)
#define	DDR_LAYOUT_START_EARLY_RESERVE_MEM		(0x5100000)

#define DDR_LAYOUT_SIZE_KERNEL		(0x02000000)
#define DDR_LAYOUT_SIZE_LOADER		(0x02000000)
#define DDR_LAYOUT_SIZE_TEEOS		(0x09800000)
#define DDR_LAYOUT_SIZE_ROOTFS		(0x01000000)
#define	DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM		(0x2800000)

#define DDR_LAYOUT_END_KERNEL		(DDR_LAYOUT_START_KERNEL + DDR_LAYOUT_SIZE_KERNEL)
#define DDR_LAYOUT_END_LOADER		(DDR_LAYOUT_START_LOADER + DDR_LAYOUT_SIZE_LOADER)
#define DDR_LAYOUT_END_TEEOS		(DDR_LAYOUT_START_TEEOS + DDR_LAYOUT_SIZE_TEEOS)
#define DDR_LAYOUT_END_ROOTFS		(DDR_LAYOUT_START_ROOTFS + DDR_LAYOUT_SIZE_ROOTFS)
#define	DDR_LAYOUT_END_EARLY_RESERVE_MEM		(DDR_LAYOUT_START_EARLY_RESERVE_MEM + DDR_LAYOUT_SIZE_EARLY_RESERVE_MEM)
/********CONFIG_ARCH_HI3716MV420N********/

#else
#error "Unknown ARCH!!!"
#endif


#endif