#ifndef __VDP_HAL_QFRAME_H__
#define __VDP_HAL_QFRAME_H__

#include "vdp_qfrm_reg.h"

#define  QF_MASK_WTUNL 1

HI_VOID VDP_QF_HAL_SetVID_STARTMODE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_OFFLINE_FPGADBG *pstOFFLINE_FPGADBG);

HI_VOID VDP_QF_HAL_SetLINK_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_LINK_CTRL *pstLINK_CTRL);

HI_VOID VDP_QF_HAL_SetPARA_ADDR_VHD_CHN00(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_PARA_ADDR_VHD_CHN00 *pstPARA_ADDR_VHD_CHN00);

HI_VOID VDP_QF_HAL_SetPARA_ADDR_VHD_CHN01(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_PARA_ADDR_VHD_CHN01 *pstPARA_ADDR_VHD_CHN01);

HI_VOID VDP_QF_HAL_SetPARA_ADDR_VHD_CHN02(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_PARA_ADDR_VHD_CHN02 *pstPARA_ADDR_VHD_CHN02);

HI_VOID VDP_QF_HAL_SetPARA_ADDR_VHD_CHN07(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_PARA_ADDR_VHD_CHN07 *pstPARA_ADDR_VHD_CHN07);

HI_VOID VDP_QF_HAL_SetPARA_ADDR_VHD_CHN08(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_PARA_ADDR_VHD_CHN08 *pstPARA_ADDR_VHD_CHN08);

HI_VOID VDP_QF_HAL_SetPARA_UP_VHD(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_PARA_UP_VHD *pstPARA_UP_VHD);

HI_VOID VDP_QF_HAL_SetV0_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_CTRL *pstV0_CTRL);

HI_VOID VDP_QF_HAL_SetFPGADEBUG_SOFTALG(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_FPGADEBUG_SOFTALG *pstFPGADEBUG_SOFTALG);

HI_VOID VDP_QF_HAL_SetV0_VPSS_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VPSS_CTRL *pstV0_VPSS_CTRL);

HI_VOID VDP_QF_HAL_SetV0_DFPOS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_DFPOS *pstV0_DFPOS);

HI_VOID VDP_QF_HAL_SetV0_DLPOS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_DLPOS *pstV0_DLPOS);

HI_VOID VDP_QF_HAL_SetV0_VFPOS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VFPOS *pstV0_VFPOS);

HI_VOID VDP_QF_HAL_SetV0_VLPOS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VLPOS *pstV0_VLPOS);

HI_VOID VDP_QF_HAL_SetV0_CCROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_CCROP *pstV0_CCROP);

HI_VOID VDP_QF_HAL_SetV0_FCROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_FCROP *pstV0_FCROP);

HI_VOID VDP_QF_HAL_SetV0_LCROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_LCROP *pstV0_LCROP);

HI_VOID VDP_QF_HAL_SetV0_HSP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HSP *pstV0_HSP);

HI_VOID VDP_QF_HAL_SetV0_HLOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HLOFFSET *pstV0_HLOFFSET);

HI_VOID VDP_QF_HAL_SetV0_HCOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HCOFFSET *pstV0_HCOFFSET);

HI_VOID VDP_QF_HAL_SetV0_VSP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VSP *pstV0_VSP);

HI_VOID VDP_QF_HAL_SetV0_VSR(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VSR *pstV0_VSR);

HI_VOID VDP_QF_HAL_SetV0_VOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VOFFSET *pstV0_VOFFSET);

HI_VOID VDP_QF_HAL_SetV0_VBOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_VBOFFSET *pstV0_VBOFFSET);

HI_VOID VDP_QF_HAL_SetV0_ZME_ORESO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_ZME_ORESO *pstV0_ZME_ORESO);

HI_VOID VDP_QF_HAL_SetV0_ZME_SHOOTCTRL_HL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_ZME_SHOOTCTRL_HL *pstV0_ZME_SHOOTCTRL_HL);

HI_VOID VDP_QF_HAL_SetV0_ZME_SHOOTCTRL_VL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_ZME_SHOOTCTRL_VL *pstV0_ZME_SHOOTCTRL_VL);

HI_VOID VDP_QF_HAL_SetVHDLTICTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDLTICTRL *pstVHDLTICTRL);

HI_VOID VDP_QF_HAL_SetVHDLTITHD(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDLTITHD *pstVHDLTITHD);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_CTRL *pstV0_HIPP_CSC_CTRL);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF00(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF00 *pstV0_HIPP_CSC_COEF00);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF01(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF01 *pstV0_HIPP_CSC_COEF01);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF02(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF02 *pstV0_HIPP_CSC_COEF02);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF10(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF10 *pstV0_HIPP_CSC_COEF10);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF11(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF11 *pstV0_HIPP_CSC_COEF11);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF12(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF12 *pstV0_HIPP_CSC_COEF12);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF20(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF20 *pstV0_HIPP_CSC_COEF20);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF21(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF21 *pstV0_HIPP_CSC_COEF21);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_COEF22(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_COEF22 *pstV0_HIPP_CSC_COEF22);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_SCALE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_SCALE *pstV0_HIPP_CSC_SCALE);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_IDC0(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_IDC0 *pstV0_HIPP_CSC_IDC0);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_IDC1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_IDC1 *pstV0_HIPP_CSC_IDC1);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_IDC2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_IDC2 *pstV0_HIPP_CSC_IDC2);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_ODC0(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_ODC0 *pstV0_HIPP_CSC_ODC0);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_ODC1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_ODC1 *pstV0_HIPP_CSC_ODC1);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_ODC2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_ODC2 *pstV0_HIPP_CSC_ODC2);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_MIN_Y(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_MIN_Y *pstV0_HIPP_CSC_MIN_Y);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_MIN_C(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_MIN_C *pstV0_HIPP_CSC_MIN_C);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_MAX_Y(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_MAX_Y *pstV0_HIPP_CSC_MAX_Y);

HI_VOID VDP_QF_HAL_SetV0_HIPP_CSC_MAX_C(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HIPP_CSC_MAX_C *pstV0_HIPP_CSC_MAX_C);

HI_VOID VDP_QF_HAL_SetV0_HPZME_HINFO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HPZME_HINFO *pstV0_HPZME_HINFO);

HI_VOID VDP_QF_HAL_SetV0_HPZME_HSP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HPZME_HSP *pstV0_HPZME_HSP);

HI_VOID VDP_QF_HAL_SetV0_HPZME_HLOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HPZME_HLOFFSET *pstV0_HPZME_HLOFFSET);

HI_VOID VDP_QF_HAL_SetV0_HPZME_HCOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HPZME_HCOFFSET *pstV0_HPZME_HCOFFSET);

HI_VOID VDP_QF_HAL_SetV0_HPZME_HL_SHOOTCTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HPZME_HL_SHOOTCTRL *pstV0_HPZME_HL_SHOOTCTRL);

HI_VOID VDP_QF_HAL_SetV0_HPZME_HC_SHOOTCTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_HPZME_HC_SHOOTCTRL *pstV0_HPZME_HC_SHOOTCTRL);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_CTRL *pstWBC_DHD0_CTRL);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_ZME_HINFO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_ZME_HINFO *pstWBC_DHD0_ZME_HINFO);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_ZME_HSP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_ZME_HSP *pstWBC_DHD0_ZME_HSP);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_ZME_HLOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_ZME_HLOFFSET *pstWBC_DHD0_ZME_HLOFFSET);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_ZME_HCOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_ZME_HCOFFSET *pstWBC_DHD0_ZME_HCOFFSET);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_HCDS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_HCDS *pstWBC_DHD0_HCDS);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_DITHER_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_DITHER_CTRL *pstWBC_DHD0_DITHER_CTRL);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_VZME_VINFO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_VZME_VINFO *pstWBC_DHD0_VZME_VINFO);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_VZME_VSP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_VZME_VSP *pstWBC_DHD0_VZME_VSP);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_VZME_VSR(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_VZME_VSR *pstWBC_DHD0_VZME_VSR);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_VZME_VOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_VZME_VOFFSET *pstWBC_DHD0_VZME_VOFFSET);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_VZME_VBOFFSET(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_VZME_VBOFFSET *pstWBC_DHD0_VZME_VBOFFSET);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_FCROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_FCROP *pstWBC_DHD0_FCROP);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_LCROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_LCROP *pstWBC_DHD0_LCROP);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_LBX_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_LBX_CTRL *pstWBC_DHD0_LBX_CTRL);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_LBX_ORESO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_LBX_ORESO *pstWBC_DHD0_LBX_ORESO);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_LBX_VFPOS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_LBX_VFPOS *pstWBC_DHD0_LBX_VFPOS);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_LBX_VLPOS(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_LBX_VLPOS *pstWBC_DHD0_LBX_VLPOS);

HI_VOID VDP_QF_HAL_SetVID_READ_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_READ_CTRL *pstVID_READ_CTRL);

HI_VOID VDP_QF_HAL_SetVID_MAC_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_MAC_CTRL *pstVID_MAC_CTRL);

HI_VOID VDP_QF_HAL_SetVID_READ_MODE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_READ_MODE *pstVID_READ_MODE);

HI_VOID VDP_QF_HAL_SetVID_OUT_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_OUT_CTRL *pstVID_OUT_CTRL);

HI_VOID VDP_QF_HAL_SetVID_MUTE_BK(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_MUTE_BK *pstVID_MUTE_BK);

HI_VOID VDP_QF_HAL_SetVID_SRC_BITW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_SRC_BITW *pstVID_SRC_BITW);

HI_VOID VDP_QF_HAL_SetVID_SRC_INFO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_SRC_INFO *pstVID_SRC_INFO);

HI_VOID VDP_QF_HAL_SetVID_SRC_RESO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_SRC_RESO *pstVID_SRC_RESO);

HI_VOID VDP_QF_HAL_SetVID_SRC_CROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_SRC_CROP *pstVID_SRC_CROP);

HI_VOID VDP_QF_HAL_SetVID_IN_RESO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_IN_RESO *pstVID_IN_RESO);

HI_VOID VDP_QF_HAL_SetVID_ADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_ADDR_L *pstVID_ADDR_L);

HI_VOID VDP_QF_HAL_SetVID_CADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_CADDR_L *pstVID_CADDR_L);



HI_VOID VDP_QF_HAL_SetVID_2BIT_ADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_2BIT_ADDR_L *pstVID_2BIT_ADDR_L);

HI_VOID VDP_QF_HAL_SetVID_2BIT_CADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_2BIT_CADDR_L *pstVID_2BIT_CADDR_L);

HI_VOID VDP_QF_HAL_SetVID_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_STRIDE *pstVID_STRIDE);

HI_VOID VDP_QF_HAL_SetVID_2BIT_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_2BIT_STRIDE *pstVID_2BIT_STRIDE);



HI_VOID VDP_QF_HAL_SetVID_WTUNL_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_WTUNL_CTRL *pstVID_WTUNL_CTRL);

HI_VOID VDP_QF_HAL_SetVID_WTUNL_ADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_WTUNL_ADDR_L *pstVID_WTUNL_ADDR_L);

HI_VOID VDP_QF_HAL_SetVF_VID_READ_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_READ_CTRL *pstVF_VID_READ_CTRL);

HI_VOID VDP_QF_HAL_SetVF_VID_READ_MODE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_READ_MODE *pstVF_VID_READ_MODE);

HI_VOID VDP_QF_HAL_SetVF_VID_OUT_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_OUT_CTRL *pstVF_VID_OUT_CTRL);

HI_VOID VDP_QF_HAL_SetVF_VID_MUTE_BK(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_MUTE_BK *pstVF_VID_MUTE_BK);

HI_VOID VDP_QF_HAL_SetVF_VID_SRC_BITW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_SRC_BITW *pstVF_VID_SRC_BITW);

HI_VOID VDP_QF_HAL_SetVF_VID_SRC_INFO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_SRC_INFO *pstVF_VID_SRC_INFO);

HI_VOID VDP_QF_HAL_SetVF_VID_SRC_RESO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_SRC_RESO *pstVF_VID_SRC_RESO);

HI_VOID VDP_QF_HAL_SetVF_VID_SRC_CROP(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_SRC_CROP *pstVF_VID_SRC_CROP);

HI_VOID VDP_QF_HAL_SetVF_VID_IN_RESO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_IN_RESO *pstVF_VID_IN_RESO);

HI_VOID VDP_QF_HAL_SetVF_VID_ADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_ADDR_L *pstVF_VID_ADDR_L);

HI_VOID VDP_QF_HAL_SetVF_VID_CADDR_L(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_CADDR_L *pstVF_VID_CADDR_L);

HI_VOID VDP_QF_HAL_SetVF_VID_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VF_VID_STRIDE *pstVF_VID_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_DI_CYC_Y_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_DI_CYC_Y_START_ADDR_LOW *pstVPSS_DI_CYC_Y_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_DI_CYC_Y_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_DI_CYC_Y_END_ADDR_LOW *pstVPSS_DI_CYC_Y_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_DI_CYC_C_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_DI_CYC_C_START_ADDR_LOW *pstVPSS_DI_CYC_C_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_DI_CYC_C_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_DI_CYC_C_END_ADDR_LOW *pstVPSS_DI_CYC_C_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_HISM_CYC_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_HISM_CYC_START_ADDR_LOW *pstVPSS_HISM_CYC_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_HISM_CYC_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_HISM_CYC_END_ADDR_LOW *pstVPSS_HISM_CYC_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_DM_CNT_CYC_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_DM_CNT_CYC_START_ADDR_LOW *pstVPSS_DM_CNT_CYC_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_DM_CNT_CYC_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_DM_CNT_CYC_END_ADDR_LOW *pstVPSS_DM_CNT_CYC_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_NR_MAD_CYC_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_MAD_CYC_START_ADDR_LOW *pstVPSS_NR_MAD_CYC_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_NR_MAD_CYC_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_MAD_CYC_END_ADDR_LOW *pstVPSS_NR_MAD_CYC_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_STATH_CYC_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_STATH_CYC_START_ADDR_LOW *pstVPSS_STATH_CYC_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_STATH_CYC_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_STATH_CYC_END_ADDR_LOW *pstVPSS_STATH_CYC_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_STATV_CYC_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_STATV_CYC_START_ADDR_LOW *pstVPSS_STATV_CYC_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_STATV_CYC_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_STATV_CYC_END_ADDR_LOW *pstVPSS_STATV_CYC_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_RGMV_CYC_START_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RGMV_CYC_START_ADDR_LOW *pstVPSS_RGMV_CYC_START_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_RGMV_CYC_END_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RGMV_CYC_END_ADDR_LOW *pstVPSS_RGMV_CYC_END_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_P1_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P1_CTRL *pstVPSS_P1_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P1_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P1_STRIDE *pstVPSS_P1_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_P2_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2_CTRL *pstVPSS_P2_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P2_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2_SIZE *pstVPSS_P2_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_P2_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2_STRIDE *pstVPSS_P2_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_P3_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P3_CTRL *pstVPSS_P3_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P3_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P3_STRIDE *pstVPSS_P3_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_RHISM_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RHISM_CTRL *pstVPSS_RHISM_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_RHISM_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RHISM_SIZE *pstVPSS_RHISM_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_RHISM_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RHISM_STRIDE *pstVPSS_RHISM_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_RDM_CNT_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RDM_CNT_CTRL *pstVPSS_RDM_CNT_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_RDM_CNT_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RDM_CNT_SIZE *pstVPSS_RDM_CNT_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_RDM_CNT_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RDM_CNT_STRIDE *pstVPSS_RDM_CNT_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_NR_RMAD_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_RMAD_CTRL *pstVPSS_NR_RMAD_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_NR_RMAD_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_RMAD_SIZE *pstVPSS_NR_RMAD_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_NR_RMAD_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_RMAD_STRIDE *pstVPSS_NR_RMAD_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_SNR_RMAD_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_SNR_RMAD_CTRL *pstVPSS_SNR_RMAD_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_SNR_RMAD_CTRL1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo,  U_VPSS_SNR_RMAD_CTRL1 *pstVPSS_SNR_RMAD_CTRL1);

HI_VOID VDP_QF_HAL_SetVPSS_SNR_RMAD_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_SNR_RMAD_STRIDE *pstVPSS_SNR_RMAD_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_P2STATH_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2STATH_CTRL *pstVPSS_P2STATH_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P2STATH_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2STATH_SIZE *pstVPSS_P2STATH_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_P2STATH_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2STATH_STRIDE *pstVPSS_P2STATH_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_P2STATV_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2STATV_CTRL *pstVPSS_P2STATV_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P2STATV_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2STATV_SIZE *pstVPSS_P2STATV_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_P2STATV_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2STATV_STRIDE *pstVPSS_P2STATV_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_P2RGMV_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2RGMV_CTRL *pstVPSS_P2RGMV_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P2RGMV_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2RGMV_SIZE *pstVPSS_P2RGMV_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_P2RGMV_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P2RGMV_STRIDE *pstVPSS_P2RGMV_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_P1RGMV_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P1RGMV_CTRL *pstVPSS_P1RGMV_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_P1RGMV_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_P1RGMV_STRIDE *pstVPSS_P1RGMV_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_RFR_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RFR_CTRL *pstVPSS_RFR_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_RFR_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_RFR_STRIDE *pstVPSS_RFR_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_WHISM_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_WHISM_CTRL *pstVPSS_WHISM_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_WHISM_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_WHISM_STRIDE *pstVPSS_WHISM_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_WHISM_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_WHISM_SIZE *pstVPSS_WHISM_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_WDM_CNT_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_WDM_CNT_CTRL *pstVPSS_WDM_CNT_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_WDM_CNT_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_WDM_CNT_STRIDE *pstVPSS_WDM_CNT_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_WDM_CNT_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_WDM_CNT_SIZE *pstVPSS_WDM_CNT_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_NR_WMAD_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_WMAD_CTRL *pstVPSS_NR_WMAD_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_NR_WMAD_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_WMAD_STRIDE *pstVPSS_NR_WMAD_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_NR_WMAD_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_NR_WMAD_SIZE *pstVPSS_NR_WMAD_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_CFSTATH_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFSTATH_CTRL *pstVPSS_CFSTATH_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_CFSTATH_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFSTATH_STRIDE *pstVPSS_CFSTATH_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_CFSTATH_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFSTATH_SIZE *pstVPSS_CFSTATH_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_CFSTATV_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFSTATV_CTRL *pstVPSS_CFSTATV_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_CFSTATV_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFSTATV_STRIDE *pstVPSS_CFSTATV_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_CFSTATV_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFSTATV_SIZE *pstVPSS_CFSTATV_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_CFRGMV_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFRGMV_CTRL *pstVPSS_CFRGMV_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_CFRGMV_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFRGMV_STRIDE *pstVPSS_CFRGMV_STRIDE);

HI_VOID VDP_QF_HAL_SetVPSS_CFRGMV_SIZE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_CFRGMV_SIZE *pstVPSS_CFRGMV_SIZE);

HI_VOID VDP_QF_HAL_SetVPSS_OUT_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_OUT_CTRL *pstVPSS_OUT_CTRL);

HI_VOID VDP_QF_HAL_SetVPSS_OUTY_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_OUTY_ADDR_LOW *pstVPSS_OUTY_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_OUTC_ADDR_LOW(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_OUTC_ADDR_LOW *pstVPSS_OUTC_ADDR_LOW);

HI_VOID VDP_QF_HAL_SetVPSS_OUT_STRIDE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_OUT_STRIDE *pstVPSS_OUT_STRIDE);

HI_VOID VDP_QF_HAL_SetVID_DTV_CFG_READY(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VID_DTV_CFG_READY *pstVID_DTV_CFG_READY);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_CTRL *pstWBC_DHD_HIPP_CSC_CTRL);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF00(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF00 *pstWBC_DHD_HIPP_CSC_COEF00);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF01(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF01 *pstWBC_DHD_HIPP_CSC_COEF01);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF02(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF02 *pstWBC_DHD_HIPP_CSC_COEF02);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF10(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF10 *pstWBC_DHD_HIPP_CSC_COEF10);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF11(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF11 *pstWBC_DHD_HIPP_CSC_COEF11);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF12(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF12 *pstWBC_DHD_HIPP_CSC_COEF12);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF20(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF20 *pstWBC_DHD_HIPP_CSC_COEF20);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF21(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF21 *pstWBC_DHD_HIPP_CSC_COEF21);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_COEF22(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_COEF22 *pstWBC_DHD_HIPP_CSC_COEF22);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_SCALE(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_SCALE *pstWBC_DHD_HIPP_CSC_SCALE);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_IDC0(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_IDC0 *pstWBC_DHD_HIPP_CSC_IDC0);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_IDC1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_IDC1 *pstWBC_DHD_HIPP_CSC_IDC1);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_IDC2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_IDC2 *pstWBC_DHD_HIPP_CSC_IDC2);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_ODC0(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_ODC0 *pstWBC_DHD_HIPP_CSC_ODC0);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_ODC1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_ODC1 *pstWBC_DHD_HIPP_CSC_ODC1);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_ODC2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_ODC2 *pstWBC_DHD_HIPP_CSC_ODC2);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_MIN_Y(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_MIN_Y *pstWBC_DHD_HIPP_CSC_MIN_Y);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_MIN_C(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_MIN_C *pstWBC_DHD_HIPP_CSC_MIN_C);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_MAX_Y(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_MAX_Y *pstWBC_DHD_HIPP_CSC_MAX_Y);

HI_VOID VDP_QF_HAL_SetWBC_DHD_HIPP_CSC_MAX_C(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD_HIPP_CSC_MAX_C *pstWBC_DHD_HIPP_CSC_MAX_C);

HI_VOID VDP_QF_HAL_SetVHDACCTHD1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCTHD1 *pstVHDACCTHD1);

HI_VOID VDP_QF_HAL_SetVHDACCTHD2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCTHD2 *pstVHDACCTHD2);

HI_VOID VDP_QF_HAL_SetVHDACCDEMO(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCDEMO *pstVHDACCDEMO);

HI_VOID VDP_QF_HAL_SetVHDACCLOW1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCLOW1 *pstVHDACCLOW1);

HI_VOID VDP_QF_HAL_SetVHDACCLOW2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCLOW2 *pstVHDACCLOW2);

HI_VOID VDP_QF_HAL_SetVHDACCLOW3(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCLOW3 *pstVHDACCLOW3);

HI_VOID VDP_QF_HAL_SetVHDACCMED1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCMED1 *pstVHDACCMED1);

HI_VOID VDP_QF_HAL_SetVHDACCMED2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCMED2 *pstVHDACCMED2);

HI_VOID VDP_QF_HAL_SetVHDACCMED3(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCMED3 *pstVHDACCMED3);

HI_VOID VDP_QF_HAL_SetVHDACCHIGH1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCHIGH1 *pstVHDACCHIGH1);

HI_VOID VDP_QF_HAL_SetVHDACCHIGH2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCHIGH2 *pstVHDACCHIGH2);

HI_VOID VDP_QF_HAL_SetVHDACCHIGH3(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACCHIGH3 *pstVHDACCHIGH3);

HI_VOID VDP_QF_HAL_SetVHDACM0(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM0 *pstVHDACM0);

HI_VOID VDP_QF_HAL_SetVHDACM1(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM1 *pstVHDACM1);

HI_VOID VDP_QF_HAL_SetVHDACM2(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM2 *pstVHDACM2);

HI_VOID VDP_QF_HAL_SetVHDACM3(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM3 *pstVHDACM3);

HI_VOID VDP_QF_HAL_SetVHDACM4(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM4 *pstVHDACM4);

HI_VOID VDP_QF_HAL_SetVHDACM5(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM5 *pstVHDACM5);

HI_VOID VDP_QF_HAL_SetVHDACM6(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM6 *pstVHDACM6);

HI_VOID VDP_QF_HAL_SetVHDACM7(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VHDACM7 *pstVHDACM7);

HI_VOID VDP_QF_HAL_SetVPSS_VC1_CTRL(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_VC1_CTRL *pstVPSS_VC1_CTRL);

HI_VOID VDP_QF_HAL_SetWBC_DHD0_UPD(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_WBC_DHD0_UPD *pstWBC_DHD0_UPD);

HI_VOID VDP_QF_HAL_SetV0_UPD(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_V0_UPD *pstV0_UPD);

HI_VOID VDP_QF_HAL_SetOFFLINE_UPD (S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_OFFLINE_UPD *pstOFFLINE_UPD);

HI_VOID VDP_QF_HAL_SetVPSS_Addr(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_REGLOAD_START_ADDR *pstVPSS_Addr);
HI_VOID VDP_QF_HAL_SetVPSSAddr_Update(S_VDP_QF_REGS_TYPE *pstCfgNode, HI_U32 u32NodeInfo, U_VPSS_REGLOAD_UP *pstVpss_Update);


#endif // __VDP_HAL_QFRAME_H__
