
KBUILD_CFLAGS   += -Werror

obj-$(CONFIG_DEVFREQ_GOV_GPU_ONDEMAND)		+= governor_utgard_ondemand.o
obj-$(CONFIG_DEVFREQ_GOV_MIDGARD_ONDEMAND)	+= governor_midgard_ondemand.o

ccflags-y += -Idrivers/devfreq
